package paint_AndrewOficial.View.enums;

public enum MenuEnuns {
    CIRCULO, QUADRADO, RETANGULO, LISTAR, APAGAR, DESENHAR, SAIR,PONTO,LOSANGULO,RETA,TRAPEZIO,TRIANGULO,TEXTO,
    SALVAR,RECUPERAR,CRIAR,EDITAR
}
